const legend = {
  dna:
  {
    Name: 0,
    cd: {
      cd01: {
        cd01r: 0,
        cd01g: 0,
        cd01b: 0,
        cd02r: 0,
        cd02g: 0,
        cd02b: 0,
        cd03r: 0,
        cd03g: 0,
        cd03b: 0,
      },
      wing: {
        wingId01cd: 0,
        wingId02cd: 0,
        wingId03cd: 0,
        wingId04cd: 0,
      },
      groom: {
        groomId01cd: 0,
        groomId02cd: 0,
        groomId03cd: 0,
        groomId04cd: 0,
      },
      tail: {
        tailId01cd: 0,
        tailId02cd: 0,
        tailId03cd: 0,
        tailId04cd: 0,
      },
      skin: {
        skinId01cd: 0,
        skinId02cd: 0,
        skinId03cd: 0,
        skinId04cd: 0,
      },
      wingGradient: {
        wingGradientActive01: 0,
        wingGradientActive02: 0,
        wingGradientActive03: 0,
        wingGradientA01cd: 0,
        wingGradientB01cd: 0,
        wingGradientC01cd: 0,
        wingGradientA02cd: 0,
        wingGradientB02cd: 0,
        wingGradientC02cd: 0,
        wingGradientA03cd: 0,
        wingGradientB03cd: 0,
        wingGradientC03cd: 0,
      },
      groomGradient: {
        groomGradientActive01: 0,
        groomGradientActive02: 0,
        groomGradientActive03: 0,
        groomGradientA01cd: 0,
        groomGradientB01cd: 0,
        groomGradientC01cd: 0,
        groomGradientA02cd: 0,
        groomGradientB02cd: 0,
        groomGradientC02cd: 0,
        groomGradientA03cd: 0,
        groomGradientB03cd: 0,
        groomGradientC03cd: 0,
      },
      tailGradient: {
        tailGradientActive01: 0,
        tailGradientActive02: 0,
        tailGradientActive03: 0,
        tailGradientA01cd: 0,
        tailGradientB01cd: 0,
        tailGradientC01cd: 0,
        tailGradientA02cd: 0,
        tailGradientB02cd: 0,
        tailGradientC02cd: 0,
        tailGradientA03cd: 0,
        tailGradientB03cd: 0,
        tailGradientC03cd: 0,
      },
      skinGradient: {
        skinGradientActive01: 0,
        skinGradientActive02: 0,
        skinGradientActive03: 0,
        skinGradientA01cd: 0,
        skinGradientB01cd: 0,
        skinGradientC01cd: 0,
        skinGradientA02cd: 0,
        skinGradientB02cd: 0,
        skinGradientC02cd: 0,
        skinGradientA03cd: 0,
        skinGradientB03cd: 0,
        skinGradientC03cd: 0,
      },
      wingStripes: {
        wingStripesActive01: 0,
        wingStripesActive02: 0,
        wingStripesActive03: 0,
        wingStripesA01cd: 0,
        wingStripesB01cd: 0,
        wingStripesC01cd: 0,
        wingStripesA02cd: 0,
        wingStripesB02cd: 0,
        wingStripesC02cd: 0,
      },
      groomStripes: {
        groomStripesActive01: 0,
        groomStripesActive02: 0,
        groomStripesActive03: 0,
        groomStripesA01cd: 0,
        groomStripesB01cd: 0,
        groomStripesC01cd: 0,
        groomStripesA02cd: 0,
        groomStripesB02cd: 0,
        groomStripesC02cd: 0,
      }, tailStripes: {
        tailStripesActive01: 0,
        tailStripesActive02: 0,
        tailStripesActive03: 0,
        tailStripesA01cd: 0,
        tailStripesB01cd: 0,
        tailStripesC01cd: 0,
        tailStripesA02cd: 0,
        tailStripesB02cd: 0,
        tailStripesC02cd: 0,
      },
      skinStripes: {
        skinStripesActive01: 0,
        skinStripesActive02: 0,
        skinStripesActive03: 0,
        skinStripesA01cd: 0,
        skinStripesB01cd: 0,
        skinStripesC01cd: 0,
        skinStripesA02cd: 0,
        skinStripesB02cd: 0,
        skinStripesC02cd: 0,
      }, wingNoise: {
        wingNoiseActive01: 0,
        wingNoiseActive02: 0,
        wingNoiseActive03: 0,
        wingNoiseA01cd: 0,
        wingNoiseB01cd: 0,
        wingNoiseC01cd: 0,
        wingNoiseA02cd: 0,
        wingNoiseB02cd: 0,
        wingNoiseC02cd: 0,
        wingNoiseA03cd: 0,
        wingNoiseB03cd: 0,
        wingNoiseC03cd: 0,
      }, groomNoise: {
        groomNoiseActive01: 0,
        groomNoiseActive02: 0,
        groomNoiseActive03: 0,
        groomNoiseA01cd: 0,
        groomNoiseB01cd: 0,
        groomNoiseC01cd: 0,
        groomNoiseA02cd: 0,
        groomNoiseB02cd: 0,
        groomNoiseC02cd: 0,
        groomNoiseA03cd: 0,
        groomNoiseB03cd: 0,
        groomNoiseC03cd: 0,
      },
      tailNoise: {
        tailNoiseActive01: 0,
        tailNoiseActive02: 0,
        tailNoiseActive03: 0,
        tailNoiseA01cd: 0,
        tailNoiseB01cd: 0,
        tailNoiseC01cd: 0,
        tailNoiseA02cd: 0,
        tailNoiseB02cd: 0,
        tailNoiseC02cd: 0,
        tailNoiseA03cd: 0,
        tailNoiseB03cd: 0,
        tailNoiseC03cd: 0,
      }, skinNoise: {
        skinNoiseActive01: 0,
        skinNoiseActive02: 0,
        skinNoiseActive03: 0,
        skinNoiseA01cd: 0,
        skinNoiseB01cd: 0,
        skinNoiseC01cd: 0,
        skinNoiseA02cd: 0,
        skinNoiseB02cd: 0,
        skinNoiseC02cd: 0,
        skinNoiseA03cd: 0,
        skinNoiseB03cd: 0,
        skinNoiseC03cd: 0,
      }, beak: {
        beakBS01: 0,
        beakBS02: 0,
        beakBS03: 0,
        beakBS04: 0,
        beakBS05: 0,
        beakBS06: 0,
        beakBS07: 0,
        beakBS08: 0,
      }, talon: {
        talonBS01: 0,
        talonBS02: 0,
        talonBS03: 0,
        talonBS04: 0,
        talonBS05: 0,
        talonBS06: 0,
        talonBS07: 0,
        talonBS08: 0,
      },
      feathers:
      {
        feathers01: 0,
        feathers02: 0,
        feathers03: 0,
        feathers04: 0,
        feathers05: 0,
        feathers06: 0,
        feathers07: 0,
        feathers08: 0
      }
    }
  }
}